apiVersion: v1
kind: Service
metadata:
  name: bg-rollout-service
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: bg-rollout

---
apiVersion: v1
kind: Service
metadata:
  name: bg-rollout-service-preview
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: bg-rollout

